name: Coding Style CI

on:
  push:

jobs:
  coding_style:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Coding Style
      run: coding-style . . > reports.log

    - name: Send teams notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "'"$(tail -n 1 reports.log | sed 's/\/home\/ndelenclos\/actions-runner\/_work\/Zappy\/Zappy\/coding-style-reports.log/dir/')"'"
        }' ${{ secrets.TEAMS_WEBHOOK }}
