name: Coding Style CI

on:
  push:

jobs:
  coding_style:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Coding Style
      run: |
        coding-style . .
        cat coding-style-report.txt
