name: Coding Style CI

on:
  push:

jobs:
  coding_style:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Coding Style
      run: coding-style . .

    - name: Send teams notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "$(cat coding-style-reports.log)"
        }' ${{ secrets.TEAMS_WEBHOOK }}
