name: Coding Style CI

on:
  push:

jobs:
  coding_style:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Coding Style
      run: |
        coding-style . .
        echo "::set-output name=cds::$(cat coding-style-reports.log)"

    - name: Send teams notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "${{ steps.coding_style.outputs.cds }}"
        }' ${{ secrets.TEAMS_WEBHOOK }}
