name: Repo Mirror CI

on:
  push:

jobs:
  push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Epitech Repository
        env:
          DESTINATION_REPO: "git@github.com:EpitechPromo2026/B-YEP-400-LIL-4-1-zappy-david.plouvier.git"
          DESTINATION_BRANCH: ${{ GITHUB_REF#refs/heads/ }}
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add destination $DESTINATION_REPO
          git push destination HEAD:$DESTINATION_BRANCH
